In [1]:
from tensorflow.keras.preprocessing.text import one_hot

### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2387, 6538, 7384, 2482],
 [2387, 6538, 7384, 7391],
 [2387, 1518, 7384, 1689],
 [4698, 3429, 2326, 7178, 1385],
 [4698, 3429, 2326, 7178, 3174],
 [7860, 2387, 3164, 7384, 7790],
 [4053, 7453, 9648, 7178]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences (Updated documentation)
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np
sent_length=8 #maximum sentence length (5 would work as well)
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2387 6538 7384 2482]
 [   0    0    0    0 2387 6538 7384 7391]
 [   0    0    0    0 2387 1518 7384 1689]
 [   0    0    0 4698 3429 2326 7178 1385]
 [   0    0    0 4698 3429 2326 7178 3174]
 [   0    0    0 7860 2387 3164 7384 7790]
 [   0    0    0    0 4053 7453 9648 7178]]


In [ ]:
## feature representation (which is 300 for google's word2vec)
dim=10

In [8]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs) #each word is represented in 10 dimensions

1/1 [==============================] - 1s 920ms/step


array([[[ 4.45198268e-04,  4.41960357e-02,  4.24199142e-02,
          2.57987902e-03,  4.46194671e-02,  1.13803521e-02,
         -2.40763072e-02,  1.71473138e-02,  2.57624313e-03,
          2.88245939e-02],
        [ 4.45198268e-04,  4.41960357e-02,  4.24199142e-02,
          2.57987902e-03,  4.46194671e-02,  1.13803521e-02,
         -2.40763072e-02,  1.71473138e-02,  2.57624313e-03,
          2.88245939e-02],
        [ 4.45198268e-04,  4.41960357e-02,  4.24199142e-02,
          2.57987902e-03,  4.46194671e-02,  1.13803521e-02,
         -2.40763072e-02,  1.71473138e-02,  2.57624313e-03,
          2.88245939e-02],
        [ 4.45198268e-04,  4.41960357e-02,  4.24199142e-02,
          2.57987902e-03,  4.46194671e-02,  1.13803521e-02,
         -2.40763072e-02,  1.71473138e-02,  2.57624313e-03,
          2.88245939e-02],
        [-4.95723151e-02,  4.24057245e-03, -1.65291205e-02,
         -1.74296387e-02,  2.96999551e-02, -1.72604695e-02,
         -4.50238585e-02,  1.99553855e-02,  1.215394

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 2387, 6538, 7384, 2482])

In [12]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 46ms/step


array([[ 0.0004452 ,  0.04419604,  0.04241991,  0.00257988,  0.04461947,
         0.01138035, -0.02407631,  0.01714731,  0.00257624,  0.02882459],
       [ 0.0004452 ,  0.04419604,  0.04241991,  0.00257988,  0.04461947,
         0.01138035, -0.02407631,  0.01714731,  0.00257624,  0.02882459],
       [ 0.0004452 ,  0.04419604,  0.04241991,  0.00257988,  0.04461947,
         0.01138035, -0.02407631,  0.01714731,  0.00257624,  0.02882459],
       [ 0.0004452 ,  0.04419604,  0.04241991,  0.00257988,  0.04461947,
         0.01138035, -0.02407631,  0.01714731,  0.00257624,  0.02882459],
       [-0.04957232,  0.00424057, -0.01652912, -0.01742964,  0.02969996,
        -0.01726047, -0.04502386,  0.01995539,  0.01215395,  0.01430179],
       [-0.00590931, -0.01976761,  0.01282277,  0.02755561,  0.01432513,
        -0.04731476, -0.0223265 , -0.04089531,  0.01349964, -0.00252204],
       [ 0.04671634,  0.04093847,  0.00794046, -0.0160282 ,  0.0022725 ,
         0.03446298, -0.01148474, -0.0321243 